version: "3.8"

services:
  backend:
    build: .
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
    command: python main.py
    networks:
      - admin_backend
      - frontend

  queue:
    build: .
    command: python consumer.py
    depends_on:
      - db
    restart: always
    networks:
      - frontend

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - frontend

networks:
  admin_backend:
    external: true
  frontend:
